
name: Deploy Infrastructure to Azure

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '.azuredevops/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set environment
      id: set_env
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "ENVIRONMENT=prod" >> $GITHUB_OUTPUT
        else
          echo "ENVIRONMENT=dev" >> $GITHUB_OUTPUT
        fi

    - name: Deploy Bicep template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: .azuredevops/deploy.bicep
        parameters: .azuredevops/${{ steps.set_env.outputs.ENVIRONMENT }}.parameters.json
        scope: resourcegroup

    - name: Azure logout
      run: |
        az logout
      if: always()