# This workflow builds and deploys a Node.js application to an Azure Web App upon commits to the main branch.
#
# Prerequisites:
# - An Azure Web App created.
# - A GitHub secret named AZURE_CREDENTIALS with the Azure credentials as it's value.
# - A GitHub secret named AZURE_WEBAPP_PUBLISH_PROFILE with the Azure publish profile as its value.

name: Deploy to Azure Workflow

on:
  push:
    branches:
      - main # Trigger on commits to the main branch
  workflow_dispatch: # Allow manual trigger

env:
  AZURE_WEBAPP_NAME: ra-portfolio
  NODE_VERSION: '18.x'

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        continue-on-error: false

      - name: Build
        run: npm run build --if-present
        continue-on-error: false

      - name: Run tests
        run: npm run test:coverage --if-present
        continue-on-error: false

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if Web App exists
        id: check_app
        shell: bash
        run: |
          EXISTS=$(az webapp list --query "[?name=='${{ env.AZURE_WEBAPP_NAME }}'].name" -o tsv)
          if [ -z "$EXISTS" ]; then
            echo "WebApp does not exist, setting CREATE_APP to true."
            echo "CREATE_APP=true" >> $GITHUB_ENV
          else
            echo "WebApp exists, no need to create."
            echo "CREATE_APP=false" >> $GITHUB_ENV
          fi

      - name: Create Web App if it does not exist
        if: steps.check_app.outputs.CREATE_APP == 'true'
        run: |
          az webapp create --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group <YourResourceGroup> --plan <YourAppServicePlan> --runtime "NODE|${{ env.NODE_VERSION }}"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./dist
