# This workflow builds and deploys a Node.js application to an Azure Web App upon commits to the main branch.
#
# Prerequisites:
# - An Azure Web App created.
# - A GitHub secret named AZURE_CREDENTIALS with the Azure credentials as its value.
# - A GitHub secret named AZURE_WEBAPP_PUBLISH_PROFILE with the Azure publish profile as its value.
# - A GitHub secret named AZURE_SUBSCRIPTION_ID with the Azure subscription ID as its value.
# - A GitHub secret named AZURE_RESOURCE_GROUP with the Azure resource group name as its value.
# - A GitHub secret named AZURE_LOCATION with the Azure location as its value.
# - A GitHub secret named AZURE_SERVICE_APP_PLAN with the Azure service app plan name as its value.
# - A GitHub secret named NODE_VERSION with the Node.js version as its value.
# - A GitHub secret named PUBLIC_URL with the public URL as its value.
# - A GitHub secret named API_URL with the API URL as its value.
# - A GitHub secret named CHROMATIC_PROJECT_TOKEN with the Chromatic project token as its value.
# - A GitHub secret named SONAR_ORGANISATION with the SonarCloud organization as its value.
# - A GitHub secret named SONAR_PROJECT_KEY with the SonarCloud project key as its value.
# - A GitHub secret named SONAR_PROJECT_NAME with the SonarCloud project name as its value.
# - A GitHub secret named TOKEN_GITHUB with the GitHub token as its value.
# - A GitHub secret named TOKEN_SONAR with the SonarCloud token as its value.

name: Deploy to Azure Workflow

on:
  push:
    branches:
      - main # Trigger on commits to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        continue-on-error: false

      - name: Build
        run: npm run build
        env:
          NODE_ENV: 'production'
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
          API_URL: ${{ secrets.API_URL }}
        continue-on-error: false

      # - name: Run lint
      #   run: npm run lint
      #   continue-on-error: false

      - name: Run tests and collect coverage
        run: npm run test:coverage
        continue-on-error: false

      - name: Run Storybook
        run: npm run storybook
        continue-on-error: false

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifact
          path: ./coverage

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-artifact
          path: ./coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANISATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.projectName=${{ secrets.SONAR_PROJECT_NAME }}
        continue-on-error: false

      - name: SonarCloud Quality Gate Check
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANISATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.qualitygate.wait=true
        continue-on-error: false

  deploy:
    needs: sonarcloud
    name: Deploy to Azure
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if Web App exists
        id: check_app
        shell: bash
        run: |
          EXISTS=$(az webapp list --query "[?name=='${{ secrets.AZURE_WEBAPP_NAME }}'].name" -o tsv)
          if [ -z "$EXISTS" ]; then
            echo "WebApp does not exist, setting CREATE_APP to true."
            echo "CREATE_APP=true" >> $GITHUB_ENV
          else
            echo "WebApp exists, no need to create."
            echo "CREATE_APP=false" >> $GITHUB_ENV
          fi

      - name: Create Web App if it does not exist
        if: steps.check_app.outputs.CREATE_APP == 'true'
        run: |
          az webapp create --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --plan ${{ secrets.AZURE_SERVICE_APP_PLAN }} --runtime "NODE|${{ secrets.NODE_VERSION }}"

      - name: Prepare prod.parameters.json
        run: |
          $json = Get-Content -Path .azuredevops/prod.parameters.json -Raw | ConvertFrom-Json
          $json.parameters.subscriptionId.value = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          $json.parameters.resourceGroupName.value = "${{ secrets.AZURE_RESOURCE_GROUP }}"
          $json.parameters.name.value = "${{ secrets.AZURE_WEBAPP_NAME }}"
          $json.parameters.location.value = "${{ secrets.AZURE_LOCATION }}"
          $json.parameters.hostingPlanName.value = "${{ secrets.AZURE_SERVICE_APP_PLAN }}"
          $json.parameters.serverFarmResourceGroup.value = "${{ secrets.AZURE_RESOURCE_GROUP }}"
          $json | ConvertTo-Json -Depth 100 | Set-Content -Path ./prod.parameters.json
        shell: pwsh

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./dist
